<!-- <!DOCTYPE html>
<html>
<head>
	<title>Sign</title>
	<meta charset="utf-8">
</head>
<body>
<form id="form-sign">
	<h2><i class="fas fa-user"></i>Créer un compte: </h2>
	<p>
		<label for="mail">Mail</label>
		<input type="text" name="mail" id="mail">
	</p>
	<p>
		<label for="pseudo">Pseudo</label>
		<input type="text" name="pseudo" id="pseudo">
	</p>
	<p>
		<label for="mdp">Mot de passe</label>
		<input type="password" name="mdp" id="mdp">
	</p>
	<button type="submit" >S'inscrire</button>
    <br>
    <a href="#">Se connecter</a>
	<a href="#">Retour</a>
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src ="boris.js"></script>
</body>
</html> -->

<!DOCTYPE html>
<html>
<head>
	<title>Log</title>
	<meta charset="utf-8">
</head>
<body>
<form id="form-login">
	<h2><i class="fas fa-user"></i>Connexion: </h2>
	<p>
		<label for="mail">Mail</label>
		<input type="text" name="mail" id="mail">
	</p>
	<p>
		<label for="mdp">Mot de passe</label>
		<input type="password" name="mdp" id="mdp">
	</p>
	<button type="submit" >Se connecter</button>
    <br>
    <a href="#">S'inscrire</a>
	<a href="#">Retour</a>
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src ="boris.js"></script>
</body>
</html>
