<!DOCTYPE html>
<html>
<head>
	<title>Login</title>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="css/style.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
</head>
<body>
<form id="form-login">
	<h2><i class="fas fa-user"></i>Se connecter: </h2>
    <p>
		<label for="nom">Nom</label>
		<input type="text" name="nom" id="nom" required>
	</p>
	<p>
		<label for="mail">Mail</label>
		<input type="text" name="mail" id="mail" required>
	</p>
	<p>
		<label for="mdp">Mot de passe</label>
		<input type="text" name="mdp" id="mdp" required>
	</p>
	<button type="submit" >Se connecter</button>
    <br>
    <a href="#">S'inscrire</a>
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src ="js/login.js"></script>
</body>
</html>



<!DOCTYPE html>
<html>
<head>
	<title>Sign</title>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="css/style.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
</head>
<body>
<form id="form-sign">
	<h2><i class="fas fa-user"></i>Créer un compte: </h2>
	<p>
		<label for="mail">Mail</label>
		<input type="text" name="mail" id="mail" required>
	</p>
	<p>
		<label for="mdp">Mot de passe</label>
		<input type="password" name="mdp" id="mdp" required>
	</p>
	<button type="submit" >S'inscrire</button>
    <br>
    <a href="#">Se connecter</a>
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src ="js/sign.js"></script>
</body>
</html>