<!-- <!DOCTYPE html>
<html>
<head>
	<title>Sign</title>
	<meta charset="utf-8">
</head>
<body>
<form id="form-sign">
	<h2><i class="fas fa-user"></i>Créer un compte: </h2>
	<p>
		<label for="mail">Mail</label>
		<input type="text" name="mail" id="mail">
	</p>
	<p>
		<label for="pseudo">Pseudo</label>
		<input type="text" name="pseudo" id="pseudo">
	</p>
	<p>
		<label for="mdp">Mot de passe</label>
		<input type="password" name="mdp" id="mdp">
	</p>
	<button type="submit" >S'inscrire</button>
    <br>
    <a href="#">Se connecter</a>
	<a href="#">Retour</a>
</form>



<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src ="boris.js"></script>
</body>
</html> -->

<!-- <!DOCTYPE html>
<html>
<head>
	<title>Log</title>
	<meta charset="utf-8">
</head>
<body>
<form id="form-login">
	<h2><i class="fas fa-user"></i>Connexion: </h2>
	<p>
		<label for="mail">Mail</label>
		<input type="text" name="mail" id="mail">
	</p>
	<p>
		<label for="mdp">Mot de passe</label>
		<input type="password" name="mdp" id="mdp">
	</p>
	<button type="submit" >Se connecter</button>
    <br>
    <a href="#">S'inscrire</a>
	<a href="#">Retour</a>
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src ="boris.js"></script>
</body>
</html> -->




<!DOCTYPE html>
<html>
<head>
	<title>Log</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link rel="stylesheet" href="boris.css">
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Luckiest+Guy" rel="stylesheet">

</head>
<body>
	<section id="smoothies">
		<div class="row justify-content-around">
			<div class="col-sm-12 col-md-12 col-lg-3">
				<h2>SMOOTHIES</h2>
			</div>
		</div>
		<div class="row justify-content-around">
			<div class="col-sm-12 col-md-12 col-lg-3">
				<article>
					<img src="img/pink_pleasure.jpg" alt="Pink pleasure">
					<h3>Pink Pleasure</h3>
				</article>
			</div>
			<div class="col-sm-12 col-md-12 col-lg-3">
				<article>
					<img src="img/grey_pleasure.jpg" alt="Grey pleasure">
					<h3>Grey Pleasure</h3>
				</article>
			</div>
			<div class="col-sm-12 col-md-12 col-lg-3">
				<article>
					<img src="img/strawberry_passion.jpg" alt="Strawberry passion">
					<h3 >Strawberry Passion</h3>
				</article>
			</div>
		</div>

		<div class="row justify-content-around">
			<div class="col-sm-12 col-md-12 col-lg-3">
				<article>
					<img src="img/green_oxydant.jpg" alt="Green oxydant">
					<h3>Green Oxydant</h3>
				</article>
			</div>
			<div class="col-sm-12 col-md-12 col-lg-3">
				<article>
					<img src="img/bubble_gum.jpg" alt="Bubble Gum">
					<h3>Bubble Gum</h3>
				</article>
			</div>
			<div class="col-sm-12 col-md-12 col-lg-3">
				<article>
					<img src="img/orange_gourmandise.jpg" alt="Orange gourmandise">
					<h3>Orange Gourmandise</h3>
				</article>
			</div>
		</div>
	</section>
</body>
</html>
