<div class="container">
    <div class="row">
        <div class="col-12 text-center">
            <img src="Ressources/assets/photos/national-smoothie.png" id="imgContact">
        </div>
        <div class="col-12 text-center">
            <h1 id="h1Connect">Se connecter</h1>
            <p >En vous connectant, vous pourrez accéder à votre liste de recette favorites et en ajouter de nouvelles à votre liste. Si vous n'avez pas de compte, vous pouvez en créer un gratuitement</p>
        </div>
        <div class="col-12 text-center">
            <form id="formConnect" class="col-lg-6 col-md-10 col-sm-12">
                <a href="inscription.php"><button type="button" id="btnCreation" class="Connect">Créer un compte</button></a>   
                <div class="" id="divConnect">
                    <input class="Connect" type="text" name="mail" id="mail" placeholder="Adresse mail">
                    <br>
                    <input class="Connect" type="password" name="password" id="password" placeholder="Mot de passe">
                    <br>
                    <button type="submit" id="btnConnect" class="Connect">Connexion</button>
                </div>
            </form>
        </div>
    </div>
</div>

