
<body>
<div class="container">
    <div class="row">
        <div class="col-12 text-center">
            <h2 class="text-center h2Contact">Localisation</h2>
        </div>

        <div class="col-12">
            
            <p>Vous voulez nous rejoindre pour déguster de bons smoothies? Mais vous ne savez pas où se trouve le Smooth Maker? Pas de panique, on vous dit tout, juste en dessous!</p>
        </div>

        <div class="col-lg-4 col-md-4 col-sm-12 text-center horaires">
            <h3>Horaires et jours d'ouverture :</h3>
            <ul>
                <li>Lundi : 8h30-19h30</li>
                <li>Mardi : 8h30-19h30</li>
                <li>Mercredi : 8h30-19h30</li>
                <li>Jeudi : 8h30-19h30</li>
                <li>Vendredi : 8h30-19h30</li>
                <li>Samedi : 8h30-19h30</li>
                <li>Dimanche : Fermé (repos oblige...)</li>
            </ul>
            <p>24 place Bellecour 69002 Lyon</p>
            <p>04-78-56-85-98</p>
            <p>smooth-maker@gmail.com</p>
        </div>

        <div class="col-lg-8 col-md-8 col-sm-12">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2783.642479572768!2d4.831943215567317!3d45.75831297910553!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47f4ea515925a4b3%3A0xe88b8f76f941cb4c!2s12+Place+Bellecour%2C+69002+Lyon!5e0!3m2!1sfr!2sfr!4v1557491016287!5m2!1sfr!2sfr" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

        </div>

        <div class="col-md-8 offset-md-2 text-center" >
            <h2 class="text-center h2Contact">Formulaire de contact</h2>
        </div>

        <div class="col-md-8 offset-md-2 col-sm-12">
            
            <p>Souhaitez-vous nous écrire? Une suggestion? Remplissez le petit formulaire juste en dessous pour nous faire part de vos idées...</p>

        </div>
        <div class="alert alert-danger" role="alert">
            
        </div>
        <div class="col-md-6 offset-md-3 col-sm-12 text-center" id="divConnect">
            <form method="post" action="contact.php">
                <input class="Connect" type="text" name="email" placeholder="Adresse mail">
                <input class="Connect" type="textarea" name="message" placeholder="Commentaire">
               
                <button type="submit" id="btnEnvoi" class="Connect">Envoyer</button>
            </form>
        </div>
    </div>
</div>
</body>
