<div class="container">
    <div class="row justify-content-around">
        <div class="col" id="favo">
        </div>
    </div><br>

    <div class="row justify-content-around">
    <div class="col-8 text-center"><p class="p text-center">Votre liste favorite</p>
    </div>
    </div>

    <div class="row justify-content-around">
    <div class="col-sm-12 col-md-12 col-lg-3"></div>
    </div>
</div>