<div class="container">
    <div class="row justify-content-around">
        <div class="col" id="favo">
        </div>
    </div><br>

    <div class="row justify-content-around">
    <div class="col-8 text-center"><p class="p text-center">Votre liste favorite</p>
    </div>
    </div>


<section id="smoothies">
<div class="row">

<?php foreach($produit as $produits): ?>
  <div class="col-sm-12 col-md-12 col-lg-4">
  
                    <article>
                    
                        <div class="fruits"> 
                               
                            <img src="<?=$produits['photos']?>" alt="Pink pleasure">
                        </div> 

                        <a href="recette_details.php?produit=<?=$produits['Id']?>" class="lienRecette">
                        <h3><strong><?=$produits['name']?></strong></h3>
                        </a>
                       
                    </article>
    
        </div>
<?php endforeach; ?>
</div>
</section>

</div>

