<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link rel="stylesheet" href="style.css">
    <title>SmothieShop</title>
</head>
<body>
    <div class="container-fluid image-accueil">
            <ul class="nav justify-content-center">
                <li class="nav-item">
                    <a class="nav-link" href="smoothies.phtml">Smoothies</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="recettes.phtml">Recettes</a>
                </li class="nav-item">
                <li class="nav-item">
                    <a class="nav-link" href="index.phtml"><img class="logo" src="Ressources/assets/logo/logoblanc.svg" alt="logo"></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="connexion.phtml">Connexion</a>
                </li>
                <li class="nav-item">
                    <a href="contact.phtml">Contact</a>
                </li>
            </ul>
        <h1>Bienvenu au Smooth Maker</h1>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script src="main.js"></script>
</body>
</html>