<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link rel="stylesheet" href="style.css">
    <title>SmothieShop</title>
</head>
<body>
    <div class="container-fluid page-entiere">
        <div class="container-fluid image-accueil">
                <ul class="nav justify-content-center">
                    <li class="nav-item">
                        <a class="nav-link" href="smoothies.phtml">Smoothies</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="recettes.phtml">Recettes</a>
                    </li class="nav-item">
                    <li class="nav-item">
                        <a class="nav-link" href="index.phtml"><img class="logo" src="Ressources/assets/logo/logoblanc.svg" alt="logo"></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="connexion.phtml">Connexion</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="contact.phtml">Contact</a>
                    </li>
                </ul>
            <h1>Bienvenue<br> Au Smooth Maker</h1>
            <button class="bouton-accueil"><a href="#sectionPrem">Découvrir</a></button>
        </div>

        <div class="container" id="sectionPrem">

        <div class="row">  

            <div class="col-6"><p class="p text-center">Qui sommes-nous?</p>

            <br>

            <p>

            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce volutpat mauris nec orci gravida, id dictum nunc dapibus. Vivamus et diam tortor. Fusce sodales nisl quam, ac tempus eros egestas et. Nulla venenatis in velit in fermentum. Suspendisse turpis neque, ornare ut turpis id, auctor lacinia erat. Nulla at placerat lectus, nec commodo turpis. 

            </p>

            <p>

            Nam volutpat vel felis at ullamcorper. Mauris laoreet,turpis vel sollicitudin rhoncus, purus lorem feugiat ex, non posuere dolor nisi quis sapien. Praesent convallis fringilla turpis sed tincidunt. Sed suscipit maximus neque, eget gravida magna venenatis sed. Vestibulum arcu lectus, suscipit id dolor eu, vestibulum sodales sapien.

            </p>

            </div>

            <div class="col-6 text-center">

                <img src="Ressources/assets/photos/smoothieVert.png">

            </div>

        </div> 

        </div>
        <section id="smoothies">
            <div class="row justify-content-around">
                <div class="col-sm-12 col-md-12 col-lg-3">
                    <h2>SMOOTHIES</h2>
                </div>
            </div>
            <div class="row justify-content-around photos-filles">
                <div class="col-sm-12 col-md-12 col-lg-3">
                    <article>
                        <img src="img/pink_pleasure.jpg" alt="Pink pleasure">
                        <h3>Pink Pleasure</h3>
                    </article>
                </div>
                <div class="col-sm-12 col-md-12 col-lg-3">
                    <article>
                        <img src="img/grey_pleasure.jpg" alt="Grey pleasure">
                        <h3>Grey Pleasure</h3>
                    </article>
                </div>
                <div class="col-sm-12 col-md-12 col-lg-3">
                    <article>
                        <img src="img/strawberry_passion.jpg" alt="Strawberry passion">
                        <h3 >Strawberry Passion</h3>
                    </article>
                </div>
            </div>

            <div class="row justify-content-around">
                <div class="col-sm-12 col-md-12 col-lg-3">
                    <article>
                        <img src="img/green_oxydant.jpg" alt="Green oxydant">
                        <h3>Green Oxydant</h3>
                    </article>
                </div>
                <div class="col-sm-12 col-md-12 col-lg-3">
                    <article>
                        <img src="img/bubble_gum.jpg" alt="Bubble Gum">
                        <h3>Bubble Gum</h3>
                    </article>
                </div>
                <div class="col-sm-12 col-md-12 col-lg-3">
                    <article>
                        <img src="img/orange_gourmandise.jpg" alt="Orange gourmandise">
                        <h3>Orange Gourmandise</h3>
                    </article>
                </div>
            </div>
        </section>
        <div class="row justify-content-around" id="bouton-nous-trouver">
            <div class="col-lg-3 col-md-12 col-sm-12">
                <h2>Où nous trouver ?</h2>
            </div>
        </div>
        <div class="row justify-content-around" id="nous-trouver">
            <div class="col-lg-3 col-md-12 col-sm-12">
                <h3>HORAIRES D'OUVERTURE :</h3>
                <p>
                    Lundi : 8h30-19h30 <br> Mardi : 8h30-19h30 <br> Mercredi : 8h30-19h30 <br> Jeudi : 8h30-19h30 <br> Vendredi : 8h30-19h30 <br> Samedi : 8h30-19h30 <br> Dimanche : Fermé (repos oblige...)
                </p>
                <p>
                    <strong>24 place Bellecour 69002 Lyon 04-78-56-85-98</strong><br> smooth-maker@gmail.com
                </p>
            </div>
            <div class="col-lg-6 col-md-12 col-sm-12">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2783.7343280770415!2d4.83023505137791!3d45.7564718218114!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47f4ea52365ce9a1%3A0xa5c1fe4e0fe5b12c!2s24+Place+Bellecour%2C+69002+Lyon!5e0!3m2!1sfr!2sfr!4v1557474026162!5m2!1sfr!2sfr" width="600" height="450" frameborder="0" style="border:0" allowfullscreen>
                </iframe>
            </div>
        </div>
        <div class="row justify-content-around" id="bouton-nous-trouver">
            <div class="col-lg-4 col-md-12 col-sm-12">
                <h2>Découvrez nos <strong>DIY</strong> SMOOTHIES</h2>
            </div>
        </div>
        <div class="row justify-content-around" id="diy">
            <div class="col-lg-2 col-md-12 col-sm-12">
                <p>
                   Nos smoothies, chez vous, par vous. Vous aimez nos smoothies ? Découvrez nos recettes à refaire chez vous !
                </p>
                <button class="bouton-diy"><a href="recettes.phtml"></a>Les recettes</button>
            </div>
            <div class="col-lg-4 col-md-12 col-sm-12">
            <img src="Ressources/assets/photos/shutterstock_256333441_ki8wbk.jpg" alt="logo">
            </div>
        </div>
    <footer>
        <p>Retrouver-nous sur les réseaux sociaux</p>
        <p>#SMOOTHMAKER</p>
        <div id="reseaux-sociaux">
            <a href="#"><i class="fab fa-facebook"></i></a>
            <a href="#"><i class="fab fa-instagram"></i></a>
            <a href="#"><i class="fab fa-twitter"></i></a>
            <a href="#"><i class="fab fa-snapchat-ghost"></i></a>
        </div>
        <div id="nav-footer">
            <a href="#">SMOOTHIES</a>
            <a href="#">RECETTES</a>
            <a href="#">CONNEXION</a>
            <a href="#">CONTACT</a>
        </div>
    </footer>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script src="main.js"></script>
</body>
</html>