<html>
<head>
	<title>Smoothies Shop</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link rel="stylesheet" href="style.css">
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Luckiest+Guy" rel="stylesheet">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

</head>
<body>
	<header>
	<?php if($template == 'index'):?>
        <div class="container-fluid image-accueil">
			<nav class="navbar changeColor navbar-expand-sm container-fluid navigation justify-content-between">
					<a class="navbar-brand d-block d-sm-none" href="index.php"><img class="logo-acceuil" src="img/logoblanc.svg" alt=""></a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
						<i class="fas fa-bars"></i>
					</button>
					<div class="collapse navbar-collapse text-right" id="navbarToggler">
						<ul class="navbar-nav mt-2 mt-lg-0 container-fluid justify-content-around align-items-center">
							<li class="nav-item">
								<a class="nav-link" href="smoothies.php">Smoothies</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="recette.php">Recettes</a>
							</li>
							<li>
								<a class="navbar-brand d-none d-md-block d-lg-block" href="index.php"><img class="logo" src="img/logoblanc.svg" alt=""></a>
							</li>
							<li class="nav-item">
								<?php 
									if($pseudo){echo("<a class='nav-link' href='deconnexion.php'>Deconnexion</a>");}
									else {echo("<a class='nav-link' href='connexion.php'>Connexion</a>");}
								?>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="contact.php">Contact</a>
							</li>
						</ul>
					</div>
				</nav>
				
				<h1>Bienvenue<br> Au Smooth Maker</h1>
                <button class="bouton-accueil"><a href="#sectionPrem">Découvrir</a></button>
				
            </div>
            <?php else:?>
				<nav class="navbar navbar-expand-md navbar-light bg-light">
					<a class="navbar-brand" href="index.php"><img class="logo" src="img/logo.svg" alt=""></a>
						<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
							<span class="navbar-toggler-icon"></span>
						</button>
					<div class="collapse navbar-collapse text-center" id="navbarToggler">
						<ul class="navbar-nav ml-auto mt-2 mt-lg-0 ">
							<li class="nav-item">
								<a class="nav-link" href="smoothies.php">Smoothies</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="recette.php">Recettes</a>
							</li>
							<li class="nav-item">
								<?php 
								if($pseudo){echo("<a class='nav-link' href='deconnexion.php'>Deconnexion</a>");}
								else {echo("<a class='nav-link' href='connexion.php'>Connexion</a>");}
								?>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="contact.php">Contact</a>
							</li>
						</ul>
					</div>
				</nav>
			<?php endif;?>
			<?php if($pseudo){echo("<p class='alert alert-success d-flex justify-content-around' id='bienvenue'>Bienvenue ".$pseudo['pseudo']." !</p>");}?>
		</header>

		<main class="container">
			<?php include $template.".phtml"?>
		</main>


		<footer>
			<p>Retrouvez-nous sur les réseaux sociaux</p>
			<p>#SMOOTHMAKER</p>
			<div id="reseaux-sociaux" class="row justify-content-center">
				<div class="col col-md-2 mt-3">
					<a href="https://fr-fr.facebook.com/"><i class="fab fa-facebook"></i></a>
				</div>
				<div class="col col-md-2 mt-3">
					<a href="https://www.instagram.com/?hl=fr"><i class="fab fa-instagram"></i></a>
				</div>
				<div class="col col-md-2 mt-3">
					<a href="https://twitter.com/login?lang=fr"><i class="fab fa-twitter"></i></a>
				</div>
				<div class="col col-md-2 mt-3">
					<a href="https://www.snapchat.com/l/fr-fr/download"><i class="fab fa-snapchat-ghost"></i></a>
				</div>
			</div>
			<div id="nav-footer" class="row justify-content-center">
				<div class="col col-sm-5 col-md-2 mt-3">
					<a href="#">SMOOTHIES</a>
				</div>
				<div class="col col-sm-5 col-md-2 mt-3">
					<a href="recette.php">RECETTES</a>
				</div>
				<div class="col col-sm-5 col-md-2 mt-3">
					<?php if($pseudo){echo("<a href='deconnexion.php'>DECONNEXION</a>");}else {
						echo("<a href='connexion.php'>CONNEXION</a>");
					}?>
				</div>
				<div class="col col-sm-5 col-md-2 mt-3">
					<a href="contact.php">CONTACT</a>
				</div>
			</div>
		</footer>
		<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script> 
		<script src="main.js"></script>
		<script src="favoris.js"></script>
		<!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	</body>
	</html>
