<div class="container">
    <div class="row justify-content-around">
        <div class="col" id="detox">
        </div>
    </div><br>

    <div class="row justify-content-around">
    <div class="col-8 text-center"><p class="p text-center">Nos recettes</p>
    <p>Des recettes simples à réaliser chez vous, au bureau, n’importe où... Que ce soit au petit-déjeuner, à votre pause de midi, pour votre goûter, nos recettes vont vous booster pour la journée. Il est préférable d’utiliser des fruits de saison !</p>
    </div>
    </div>

    <div class="row justify-content-around">
    <div class="col-5 text-center lien">
        <a href="favoriss.php"><img src="Ressources/assets/icons/emptyheart.png" alt="" class="heart">Vos recettes favorites</a>
    </div>
    </div>
</div>

<section id="smoothies">
            
            <div class="row justify-content-around photos-filles">
                <div class="col-sm-12 col-md-12 col-lg-3">
                    <article>
                        <img src="img/pink_pleasure.jpg" alt="Pink pleasure">
                        <h3><strong>Pink Pleasure</strong></h3>
                    </article>
                </div>
                <div class="col-sm-12 col-md-12 col-lg-3">
                    <article>
                        <img src="img/grey_pleasure.jpg" alt="Grey pleasure">
                        <h3><strong>Grey Pleasure</strong></h3>
                    </article>
                </div>
                <div class="col-sm-12 col-md-12 col-lg-3">
                    <article>
                        <img src="img/strawberry_passion.jpg" alt="Strawberry passion">
                        <h3><strong>Strawberry Passion</strong></h3>
                    </article>
                </div>
            </div>

            <div class="row justify-content-around">
                <div class="col-sm-12 col-md-12 col-lg-3">
                    <article>
                        <img src="img/green_oxydant.jpg" alt="Green oxydant">
                        <h3><strong>Green Oxydant</strong></h3>
                    </article>
                </div>
                <div class="col-sm-12 col-md-12 col-lg-3">
                    <article>
                        <img src="img/bubble_gum.jpg" alt="Bubble Gum">
                        <h3><strong>Bubble Gum</strong></h3>
                    </article>
                </div>
                <div class="col-sm-12 col-md-12 col-lg-3">
                    <article>
                        <img src="img/orange_gourmandise.jpg" alt="Orange gourmandise">
                        <h3><strong>Orange Gourmandise</strong></h3>
                    </article>
                </div>
            </div>
</section>

<section id="smoothies">
            
            <div class="row justify-content-around photos-filles">
                <div class="col-sm-12 col-md-12 col-lg-3">
                    <article>
                        <img src="img/smooth.jpg" alt="Pink pleasure">
                        <h3><strong>Pink lips</strong></h3>
                    </article>
                </div>
                <div class="col-sm-12 col-md-12 col-lg-3">
                    <article>
                        <img src="img/grey_pleasure.jpg" alt="Grey pleasure">
                        <h3><strong>Grey fit</strong></h3>
                    </article>
                </div>
                <div class="col-sm-12 col-md-12 col-lg-3">
                    <article>
                        <img src="img/strawberry_passion.jpg" alt="Strawberry passion">
                        <h3><strong>Strawberry love</strong></h3>
                    </article>
                </div>
            </div>

            <div class="row justify-content-around">
                <div class="col-sm-12 col-md-12 col-lg-3">
                    <article>
                        <img src="img/green_oxydant.jpg" alt="Green oxydant">
                        <h3><strong>Green passion</strong></h3>
                    </article>
                </div>
                <div class="col-sm-12 col-md-12 col-lg-3">
                    <article>
                        <img src="img/bubble_gum.jpg" alt="Bubble Gum">
                        <h3><strong>Bubble trouble</strong></h3>
                    </article>
                </div>
                <div class="col-sm-12 col-md-12 col-lg-3">
                    <article>
                        <img src="img/orange_gourmandise.jpg" alt="Orange gourmandise">
                        <h3><strong>Orange sanguinolante</strong></h3>
                    </article>
                </div>
            </div>
</section>

