<div id="recette-details">
    <img src="img/pink_pleasure.jpg" alt="pink_pleasure">
    
    <div class="row justify-content-center">
        <h2>PINK PLEASURE</h2>
    </div>

    <div class="row justify-content-center align-items-stretch">
        <div class="col-sm-12 col-md-3 col-lg-3 d-flex justify-content-center">
            <aside id="ingredients">
                <h4>Pour 2 personnes</h4>
                <ul>
                    <li>100gr de framboises</li>
                    <li>1 pomme</li>
                    <li>2cl de citron vert</li>
                    <li>20gr de glaçons</li>
                    <li>20gr de myrtilles</li>
                </ul>
            </aside>
        </div>
        <div class="col-sm-12 col-md-8 col-lg-8">
            <section id="realisation">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed commodo ultricies fringilla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sodales tincidunt finibus. Proin maximus auctor bibendum. Proin leo nisi, rutrum gravida massa vitae, aliquet iaculis dolor. </p>

                <h3>Etapes de réalisation :</h3>

                <ol>
                    <li>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed commodo ultricies fringilla.
                    </li>
                    <li>
                        Sed sodales tincidunt finibus. Proin maximus auctor bibendum.
                    </li>
                    <li>
                        Morbi semper ex molestie maximus condimentum. Fusce ex risus, vestibulum eu imperdiet sed, scelerisque lacinia erat.
                    </li>
                    <li>
                        Vestibulum venenatis sapien mauris, ac pulvinar massa sagittis vel.
                    </li>
                </ol>

                <p> Donec mollis, turpis gravida interdum rutrum, sem lectus cursus massa, vitae vestibulum ligula risus in eros. Phasellus vel convallis ante. Morbi nec posuere ligula. Aenean quam quam, auctor ac mattis quis, posuere id ipsum. Fusce vel mauris turpis. Integer sit amet molestie lacus. Aliquam erat volutpat. Pellentesque in ex congue, molestie sapien nec, placerat lacus.</p>
            </section>
        </div>
        <div class="row justify-content-center">
            <a href="favoris.php"><button type="button"><img src="Ressources/assets/icons/emptyheart.png" alt="" >Ajouter en favoris</button></a>
        </div>
    </div>
</div>




