<div class="container">
    <div class="row justify-content-around">
        <div class="col" id="detox">
        </div>
    </div><br>

    <div class="row justify-content-around">
    <div class="col-8 text-center"><p class="p text-center">Nos recettes</p>
    <p>Des recettes simples à réaliser chez vous, au bureau, n’importe où... Que ce soit au petit-déjeuner, à votre pause de midi, pour votre goûter, nos recettes vont vous booster pour la journée. Il est préférable d’utiliser des fruits de saison !</p>
    </div>
    </div>

    <div class="row justify-content-around">
    <div class="col-5 text-center lien">
        <a href="favoris.php"><img src="Ressources/assets/icons/emptyheart.png" alt="" class="heart">Vos recettes favorites</a>
    </div>
    </div>
</div>

<section id="smoothies">
<div class="row">

<?php foreach($produits as $produit): ?>
  <div class="col-sm-12 col-md-12 col-lg-4">
  
                    <article>
                    
                        <div class="fruits">
                            <p class="panier">
                            
                        <?=count(explode(',' ,$produit['ingredients']));?>

                            
                            <img src="Ressources/assets/icons/fruits.png" alt="" ></p>
                            <?php if($allFavoris && in_array("pink_pleasure", $allFavoris)): ?>
                                <img src="Ressources/assets/icons/fullheart.png" alt="" id="pink_pleasure" class="coeur">
                            <?php else: ?>
                                <img src="Ressources/assets/icons/emptyheart.png" alt="" id="pink_pleasure" class="coeur">
                            <?php endif; ?>
                            <img src="<?=$produit['photos']?>" alt="Pink pleasure">
                        </div>

                        <a href="recette_details.php?produit=<?=$produit['Id']?>" class="lienRecette">
                        <h3><strong><?=$produit['name']?></strong></h3>
                        </a>
                       
                    </article>
    
        </div>
<?php endforeach; ?>
</div>
</section>
