<div class="container">
    <div class="row justify-content-around">
        <div class="col" id="detox">
        </div>
    </div><br>

    <div class="row justify-content-around">
    <div class="col-8 text-center"><p class="p text-center">Notre gamme de smoothie</p>
    <p><br>Des smoothies 100% fait maison, avec des produits frais garantis Eco-responsables. Venez vite découvrir notre gamme, laissez vous emporter par un plaisir fraîchement agréable !</p><br>
    </div>
    </div>

</div>

<section id="smoothies">
<div class="row">

<?php foreach($produits as $produit): ?>
  <div class="col-sm-12 col-md-12 col-lg-4">
  
                    <article>
                    
                        <div class="fruits"> 
                               
                            <img src="<?=$produit['photos']?>" alt="Pink pleasure">
                        </div> 

                        <a href="recette_details.php?produit=<?=$produit['Id']?>" class="lienRecette">
                        <h3><strong><?=$produit['name']?></strong></h3>
                        </a>
                       
                    </article>
    
        </div>
<?php endforeach; ?>
</div>
</section>

